from __future__ import annotations

ENGLISH_STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "been", "but", "by", "for",
    "from", "has", "have", "he", "her", "his", "in", "is", "it", "its", "of",
    "on", "or", "that", "the", "their", "there", "these", "they", "this", "to",
    "was", "were", "will", "with", "we", "you", "your", "our", "about", "into",
    "over", "after", "before", "between", "new", "more", "than", "also", "very",
}

AMHARIC_STOPWORDS = {
    "እና", "ወደ", "ከ", "በ", "ለ", "ስለ", "እስከ", "እየ", "እንደ", "ነው", "ነበር",
    "ይህ", "ያ", "ይህን", "ያን", "ይህች", "ሲ", "እሱ", "እሷ", "እኛ", "እናንተ",
    "ነበሩ", "የ", "ላይ", "በተጨማሪ", "ደግሞ", "አንድ", "እንዲሁ", "ብቻ", "በጣም",
}

ENGLISH_TO_AMHARIC = {
    "school": ["ትምህርት", "ትምህርት ቤት"],
    "education": ["ትምህርት"],
    "classroom": ["ክፍል"],
    "teacher": ["መምህር", "መምህራን"],
    "student": ["ተማሪ", "ተማሪዎች"],
    "learn": ["መማር"],
    "health": ["ጤና"],
    "clinic": ["ክሊኒክ"],
    "hospital": ["ሆስፒታል"],
    "medicine": ["መድሃኒት"],
    "patient": ["ታካሚ"],
    "vaccination": ["ክትባት"],
    "water": ["ውሃ"],
    "clean": ["ንፁህ", "ንፅህና"],
    "sanitation": ["ንፅህና"],
    "well": ["ጉድጓድ"],
    "electricity": ["መብራት", "ኤሌክትሪክ"],
    "power": ["ኃይል"],
    "light": ["መብራት"],
    "service": ["አገልግሎት"],
    "road": ["መንገድ", "መንገዱ"],
    "bridge": ["ድልድይ", "ድልድዩ"],
    "transport": ["ትራንስፖርት"],
    "market": ["ገበያ", "ገበያው"],
    "agriculture": ["ግብርና"],
    "farmer": ["ገበሬ", "ገበሬዎች"],
    "irrigation": ["መስኖ"],
    "crop": ["ሰብል"],
    "harvest": ["መከር"],
    "forest": ["ደን"],
    "rainfall": ["ዝናብ"],
    "development": ["ልማት"],
    "government": ["መንግስት"],
    "budget": ["በጀት"],
    "technology": ["ቴክኖሎጂ"],
    "internet": ["ኢንተርኔት"],
    "digital": ["ዲጂታል"],
    "housing": ["መኖሪያ"],
    "job": ["ስራ"],
    "jobs": ["ስራዎች"],
    "environment": ["አካባቢ"],
}

AMHARIC_TO_ENGLISH = {
    "ትምህርት": ["education", "school"],
    "ትምህርት ቤት": ["school"],
    "ክፍል": ["classroom"],
    "መምህር": ["teacher"],
    "መምህራን": ["teacher"],
    "ተማሪ": ["student"],
    "ተማሪዎች": ["student"],
    "መማር": ["learn", "education"],
    "ጤና": ["health"],
    "ክሊኒክ": ["clinic"],
    "ሆስፒታል": ["hospital"],
    "መድሃኒት": ["medicine"],
    "ታካሚ": ["patient"],
    "ክትባት": ["vaccination"],
    "ውሃ": ["water"],
    "ንፁህ": ["clean"],
    "ንፅህና": ["sanitation", "clean"],
    "ጉድጓድ": ["well"],
    "መብራት": ["electricity", "light"],
    "ኤሌክትሪክ": ["electricity"],
    "ኃይል": ["power"],
    "አገልግሎት": ["service"],
    "መንገድ": ["road"],
    "መንገዱ": ["road"],
    "ድልድይ": ["bridge"],
    "ድልድዩ": ["bridge"],
    "ትራንስፖርት": ["transport"],
    "ገበያ": ["market"],
    "ገበያው": ["market"],
    "ግብርና": ["agriculture"],
    "ገበሬ": ["farmer"],
    "ገበሬዎች": ["farmer"],
    "መስኖ": ["irrigation"],
    "ሰብል": ["crop"],
    "መከር": ["harvest"],
    "ደን": ["forest"],
    "ዝናብ": ["rainfall"],
    "ልማት": ["development"],
    "መንግስት": ["government"],
    "በጀት": ["budget"],
    "ቴክኖሎጂ": ["technology"],
    "ኢንተርኔት": ["internet"],
    "ዲጂታል": ["digital"],
    "መኖሪያ": ["housing"],
    "ስራ": ["job"],
    "ስራዎች": ["jobs"],
    "አካባቢ": ["environment"],
}

TERM_GROUPS = {
    "school": {"education", "classroom", "teacher", "student", "ትምህርት", "ትምህርት ቤት", "ክፍል", "መምህር", "መምህራን", "ተማሪ", "ተማሪዎች"},
    "health": {"clinic", "hospital", "medicine", "patient", "vaccination", "ጤና", "ክሊኒክ", "ሆስፒታል", "መድሃኒት", "ታካሚ", "ክትባት"},
    "water": {"clean", "sanitation", "well", "ውሃ", "ንፁህ", "ንፅህና", "ጉድጓድ"},
    "electricity": {"power", "light", "service", "መብራት", "ኤሌክትሪክ", "ኃይል", "አገልግሎት"},
    "transport": {"road", "bridge", "market", "ትራንስፖርት", "መንገድ", "መንገዱ", "ድልድይ", "ድልድዩ", "ገበያ", "ገበያው"},
    "agriculture": {"farmer", "irrigation", "crop", "harvest", "forest", "rainfall", "ግብርና", "ገበሬ", "ገበሬዎች", "መስኖ", "ሰብል", "መከር", "ደን", "ዝናብ"},
    "development": {"government", "budget", "technology", "internet", "digital", "housing", "job", "jobs", "environment", "ልማት", "መንግስት", "በጀት", "ቴክኖሎጂ", "ኢንተርኔት", "ዲጂታል", "መኖሪያ", "ስራ", "ስራዎች", "አካባቢ"},
}
